### ISSUE TITLE
Configure Postgres for UTF-8

### ISSUE THREAD

**Issue by gulopine** [heroku/heroku-buildpack-ci-postgresql#2]
When setting up this buildpack for Heroku Connect, I initially had trouble with some of our Unicode tests, which we eventually tracked down to the fact that the default Postgres database was using `C` for its locale settings (`LC_CTYPE` and `LC_COLLATE`, for example), while the databases created by the Heroku Postgres addon use `en_us.UTF-8`. We were able to get the database to use the correct encoding by setting the following env vars in our CI configuration:

* `LANG=en_us.UTF-8`
* `LC_CTYPE=en_us.UTF-8`
* `LC_COLLATE=en_us.UTF-8`

It might've been more than we need, or we might need to do more in the long run, but this was at least enough to get our tests working again. It'd be nice if this could be set correctly via the buildpack, directly.

**Comment by uhoh-itsmaciek** [comment]
I think we only set `LANG` in Heroku Postgres, but this definitely makes sense.
