### ISSUE TITLE
Change default PostgreSQL version from 13 to 14

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-ci-postgresql#55]
PostgreSQL 14 is now the default for Heroku PostgreSQL addons:
https://devcenter.heroku.com/changelog-items/2445

...so this buildpack's default should be updated to match:
https://github.com/heroku/heroku-buildpack-ci-postgresql/blob/79d3bc45737d8661815968a459c975defb30852e/bin/compile#L21

Ideally this would be in the playbook for new PG version releases (I don't see this work tracked in the GUS epic, so presume it's not in the playbook) :-)

cc @kbarber @beanieboi

**Comment by kbarber** [comment]
@edmorley noted, did you want us to fix this?

**Comment by edmorley** [comment]
@kbarber Ideally :-) (Languages does not own this buildpack)

**Comment by iriberri** [comment]
This was addressed at https://github.com/heroku/heroku-buildpack-ci-postgresql/pull/56.

Thanks!
